version: '3.8'
services:
  app:
    container_name: ${APP_HOST}
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - soundunion-network

  mysql:
    container_name: ${DB_HOST}
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro
      - ./database/conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - soundunion-network

volumes:
  mysql_data:

networks:
  soundunion-network:
    driver: bridge
